FIX: Updating url creation function
algorithms-in-action/algorithms-in-action.github.io pull request #80
Opened 2024-10-11 04:41 UTC by MinniMinMin

### What's Changed

Updating the url creation function:

- Logic is now in new file - 'urlCreator.js' in mid-panel folder. Contains the old switch statement that was previously found in the index file. Index.js now calls the function instead of containing it

![image](https://github.com/user-attachments/assets/d4391127-61c5-49e5-b15a-eb5b5c106a3a)

![image](https://github.com/user-attachments/assets/66c9aaeb-f2b8-4eb5-820e-a5d2a6d0fde4)

Logic for creating the url remains the same, updated documentation can be found on: 
https://human-gpt.atlassian.net/wiki/spaces/trial/pages/16908292/Share+Button

2024-10-19 11:14 UTC, MaryHuang8 commented
@MinniMinMin Please rename the PR title to containing only one action keyword 😄 
Also push the guideline document to under `docs`, and specify the name and location for it. This is because not everyone would have access to our Confluence 🫶.
PR message otherwise looking good!

2024-10-19 16:34 UTC, MaryHuang8 commented
Thanks @MinniMinMin!
@Sraccity Ready for review :))

2024-10-21 03:46 UTC, Sraccity requested changes
# *Nitpick*: Requesting Visual Changes 

**Kudos**: On getting the PR up  @MinniMinMin 

## **Bug** (Visual): Menu button color 

"Menu" Button doesn't change according to the system's color. 

> (If changes take too long, just let me know. Try to focus on other subjects work)

![image](https://github.com/user-attachments/assets/76ef86cd-01f1-4f39-9bd4-3127c7fc07ac)

2024-10-23 08:36 UTC, MinniMinMin commented
> # _Nitpick_: Requesting Visual Changes
> **Kudos**: On getting the PR up @MinniMinMin
> 
> ## **Bug** (Visual): Menu button color
> "Menu" Button doesn't change according to the system's color.
> 
> > (If changes take too long, just let me know. Try to focus on other subjects work)
> 
> ![image](https://private-user-images.githubusercontent.com/54257761/378266767-76ef86cd-01f1-4f39-9bd4-3127c7fc07ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzI1NjgsIm5iZiI6MTcyOTY3MjI2OCwicGF0aCI6Ii81NDI1Nzc2MS8zNzgyNjY3NjctNzZlZjg2Y2QtMDFmMS00ZjM5LTliZDQtMzEyN2M3ZmMwN2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZWQyODYyOGQ1YTMyMjYzYTdhZGY0MWM1MjFhNDRhZTlhNjY4Y2EyYTAyM2QwOTEzYzQwMTgwNWNjNjM2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7CDIMypRZTnjq3U_Qe6e06aCt60r_3tPuwgvwhWYHkY)

Hey @Sraccity, the code should now be updated so the menu button follows the system theme, LMK if there's more changes required/requested, TY!

![image](https://github.com/user-attachments/assets/0fb7807e-ae8d-4836-bd0b-ff4089ebf8e5)

![image](https://github.com/user-attachments/assets/d716a856-922c-4ca5-a250-36fe65d71a68)

2024-11-15 06:52 UTC, Sraccity approved these changes
Well done. Imma merge it through. 

Cheers!

Some comments are in Mandarin but it is aite. Imma change it later*

(* Hopefully)

2024-11-15 06:52 UTC, Sraccity commented on src/styles/App.scss
> +	/* 或者您想要的宽度 */
Translation: or the width you want

2024-11-15 06:52 UTC, Sraccity commented on src/styles/App.scss
> +	/* 隐藏拖动手柄 */
Translation: Hide drag handles

2024-11-15 06:52 UTC, Sraccity commented on src/styles/App.scss
> +	/* 假设右侧面板宽度为 300px，根据实际情况调整 */
Translations:

/* Adjust this value to match the new header height */
left: 0;
width: calc(100% - 300px);
/* Assume that the width of the right panel is 300px, adjust it according to the actual situation */

2024-11-15 06:53 UTC, merged